# -*- coding: utf-8 -*-
"""CODSOFT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAABKJo4Tstj7_bX5I1UzMZmzsYvG9f8
"""

import json

TASKS_FILE = "tasks.json"

def load_tasks():
    try:
        with open(TASKS_FILE, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return []

def save_tasks(tasks):
    with open(TASKS_FILE, "w") as f:
        json.dump(tasks, f, indent=2)

def show_tasks(tasks):
    if not tasks:
        print("No tasks found.")
    for i, task in enumerate(tasks):
        status = "✓" if task["completed"] else "✗"
        print(f"{i + 1}. [{status}] {task['title']}")

def add_task(tasks, title):
    tasks.append({"title": title, "completed": False})
    print("Task added!")

def mark_complete(tasks, index):
    if 0 <= index < len(tasks):
        tasks[index]["completed"] = True
        print("Task marked as completed!")

def delete_task(tasks, index):
    if 0 <= index < len(tasks):
        tasks.pop(index)
        print("Task deleted!")

def update_task(tasks, index, new_title):
    if 0 <= index < len(tasks):
        tasks[index]["title"] = new_title
        print("Task updated!")

tasks = load_tasks()
show_tasks(tasks)

add_task(tasks, "Study Python")
save_tasks(tasks)
show_tasks(tasks)

mark_complete(tasks, 0)
save_tasks(tasks)
show_tasks(tasks)

update_task(tasks, 0, "Review Python basics")
save_tasks(tasks)
show_tasks(tasks)

delete_task(tasks, 0)
save_tasks(tasks)
show_tasks(tasks)