# -*- coding: utf-8 -*-
"""CODSOFT4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9pQmxEFHSYb_kY0v1L4e9EMu0EKKB1x
"""

import random

def get_computer_choice():
    return random.choice(["rock", "paper", "scissors"])

def get_user_choice():
    choice = input("Choose rock, paper, or scissors: ").lower()
    while choice not in ["rock", "paper", "scissors"]:
        print("Invalid choice. Please try again.")
        choice = input("Choose rock, paper, or scissors: ").lower()
    return choice

def determine_winner(user, computer):
    if user == computer:
        return "tie"
    elif (user == "rock" and computer == "scissors") or \
         (user == "scissors" and computer == "paper") or \
         (user == "paper" and computer == "rock"):
        return "user"
    else:
        return "computer"

def play_round():
    user = get_user_choice()
    computer = get_computer_choice()

    print(f"\nYou chose: {user}")
    print(f"Computer chose: {computer}")

    result = determine_winner(user, computer)

    if result == "tie":
        print("It's a tie!")
    elif result == "user":
        print("You win! 🎉")
    else:
        print("Computer wins. 🤖")

    return result

def main():
    print("🎮 Welcome to Rock-Paper-Scissors!")
    user_score = 0
    computer_score = 0
    round_number = 1

    while True:
        print(f"\n--- Round {round_number} ---")
        result = play_round()

        if result == "user":
            user_score += 1
        elif result == "computer":
            computer_score += 1

        print(f"\nScore => You: {user_score} | Computer: {computer_score}")

        play_again = input("\nDo you want to play again? (yes/no): ").lower()
        if play_again != "yes":
            print("\nThanks for playing! Final Score:")
            print(f"You: {user_score} | Computer: {computer_score}")
            break

        round_number += 1

# Run the game
main()