# -*- coding: utf-8 -*-
"""CODSOFT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhRAlspf04gVN6166uBfesSFWcPKYQC-
"""

def calculator():
    print("Welcome to the Simple Calculator")

    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))
    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return

    print("Select operation:")
    print("1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")

    operation = input("Enter the operation symbol (+, -, *, /): ")

    if operation == '+':
        result = num1 + num2
    elif operation == '-':
        result = num1 - num2
    elif operation == '*':
        result = num1 * num2
    elif operation == '/':
        if num2 == 0:
            print("Error: Cannot divide by zero.")
            return
        result = num1 / num2
    else:
        print("Invalid operation selected.")
        return

    print(f"Result: {num1} {operation} {num2} = {result}")

# Run the calculator
calculator()