# -*- coding: utf-8 -*-
"""CODSOFT3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbmGM6VCgzxEpU_wqo8MlPU3TTPT6mz3
"""

import random
import string

def generate_password(length):
    if length < 4:
        print("Password length should be at least 4 for better security.")
        return None

    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def main():
    print("🔐 Welcome to the Password Generator")
    try:
        length = int(input("Enter desired password length: "))
        password = generate_password(length)
        if password:
            print(f"Generated Password: {password}")
    except ValueError:
        print("Please enter a valid number.")

# Run the generator
main()