# -*- coding: utf-8 -*-
"""CODSOFT5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vE3lpu0IshzwttSp11C019i3VbehJXd
"""

contacts = []

def add_contact():
    name = input("Enter name: ")
    phone = input("Enter phone number: ")
    email = input("Enter email: ")
    address = input("Enter address: ")
    contact = {"name": name, "phone": phone, "email": email, "address": address}
    contacts.append(contact)
    print("Contact added successfully!")

def view_contacts():
    if not contacts:
        print("No contacts found.")
        return
    print("\n--- Contact List ---")
    for i, contact in enumerate(contacts, 1):
        print(f"{i}. {contact['name']} - {contact['phone']}")

def search_contact():
    query = input("Search by name or phone: ").lower()
    found = False
    for contact in contacts:
        if query in contact["name"].lower() or query in contact["phone"]:
            print("\n--- Contact Found ---")
            print(f"Name   : {contact['name']}")
            print(f"Phone  : {contact['phone']}")
            print(f"Email  : {contact['email']}")
            print(f"Address: {contact['address']}")
            found = True
    if not found:
        print("No contact found with that name or phone.")

def update_contact():
    name = input("Enter the name of the contact to update: ").lower()
    for contact in contacts:
        if contact["name"].lower() == name:
            print("Leave any field empty to keep the current value.")
            new_name = input("New name: ") or contact["name"]
            new_phone = input("New phone: ") or contact["phone"]
            new_email = input("New email: ") or contact["email"]
            new_address = input("New address: ") or contact["address"]
            contact.update({"name": new_name, "phone": new_phone, "email": new_email, "address": new_address})
            print("Contact updated successfully!")
            return
    print("Contact not found.")

def delete_contact():
    name = input("Enter the name of the contact to delete: ").lower()
    for contact in contacts:
        if contact["name"].lower() == name:
            contacts.remove(contact)
            print("Contact deleted successfully.")
            return
    print("Contact not found.")

def menu():
    while True:
        print("\n📒 Contact Book Menu:")
        print("1. Add Contact")
        print("2. View Contacts")
        print("3. Search Contact")
        print("4. Update Contact")
        print("5. Delete Contact")
        print("6. Exit")

        choice = input("Choose an option (1-6): ")

        if choice == "1":
            add_contact()
        elif choice == "2":
            view_contacts()
        elif choice == "3":
            search_contact()
        elif choice == "4":
            update_contact()
        elif choice == "5":
            delete_contact()
        elif choice == "6":
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Please select from 1 to 6.")

# Run the program
menu()